# Generated by Django 5.2 on 2025-04-30 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_alter_addtask_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/')),
            ],
        ),
        migrations.AlterField(
            model_name='addtask',
            name='deadline',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 5, 7, 12, 38, 46, 336789, tzinfo=datetime.timezone.utc)),
        ),
    ]
